exports.linkedinAddress = 'https://www.linkedin.com/in/techie-sam'
exports.twitterAddress = 'https://twitter.com/techie_sam'
exports.githubAddress = 'https://github.com/techie-sam'
exports.whatsappLink = 'https://wa.me/+2349061918327'
exports.emailAddress = 'mailto:blessingabolade15@gmail.com'